// Punto de entrada de la biblioteca: sólo exporta (no hay main).
export { ErrorDeDominio } from './comun/ErrorDeDominio';
export type * from './interfaces/Datos';
export type * from './interfaces/IImprimible';
export type * from './interfaces/IEstadoProceso';
export type * from './interfaces/IEntradaSalida';
export type * from './interfaces/IProceso';
export type * from './interfaces/IMemoria';
export type * from './interfaces/IPlanificacion';
export type * from './interfaces/IMetricas';
export type * from './interfaces/ISimulador';
export { Proceso } from './procesos/Proceso';
export { EntradaSalida } from './procesos/EntradaSalida';
export { SinEntradaSalida } from './procesos/SinEntradaSalida';
export { EstadoProceso } from './procesos/estados/EstadoProceso';
export { Nuevo } from './procesos/estados/Nuevo';
export { EsperandoMemoria } from './procesos/estados/EsperandoMemoria';
export { Listo } from './procesos/estados/Listo';
export { Ejecutando } from './procesos/estados/Ejecutando';
export { Bloqueado } from './procesos/estados/Bloqueado';
export { Terminado } from './procesos/estados/Terminado';
export { BloqueMemoria } from './memoria/BloqueMemoria';
export { AdministradorMemoria } from './memoria/AdministradorMemoria';
export { PoliticaAsignacion } from './memoria/politicas/PoliticaAsignacion';
export { PrimerAjuste } from './memoria/politicas/PrimerAjuste';
export { MejorAjuste } from './memoria/politicas/MejorAjuste';
export { PeorAjuste } from './memoria/politicas/PeorAjuste';
export { PlanificadorRoundRobin } from './planificacion/PlanificadorRoundRobin';
export { ReglaFinalizacion } from './planificacion/reglas/ReglaFinalizacion';
export { ReglaEntradaSalida } from './planificacion/reglas/ReglaEntradaSalida';
export { ReglaQuantumAgotado } from './planificacion/reglas/ReglaQuantumAgotado';
export { ReglaContinuar } from './planificacion/reglas/ReglaContinuar';
export { Metricas } from './metricas/Metricas';
export { Simulador } from './Simulador';
